import 'dart:convert';
import 'dart:io';

import 'package:bambuddy_mobile/core/models/process_option.dart';
import 'package:bambuddy_mobile/core/slicer/process_schema_catalog.dart';
import 'package:flutter_test/flutter_test.dart';

/// The vendored OrcaSlicer metadata against the invariants the process-settings
/// screen depends on.
///
/// These files are a copy of a copy — generated by the bambuddy server from
/// OrcaSlicer's C++ sources, then copied here (`assets/slicer/PROVENANCE`). The
/// point of this suite is that a **re-vendor** which breaks the screen fails
/// here, loudly, instead of shipping: an option added to the schema but not to
/// the tree is unreachable, one in the tree but not the schema renders as an
/// empty row, and a new option type falls through to a control that writes a
/// value the slicer silently drops.
///
/// Counts are deliberately asserted as floors, not exact numbers: OrcaSlicer
/// gaining an option is normal and must not turn this suite red. The structural
/// invariants below are what actually has to hold.
void main() {
  late ProcessSchemaCatalog catalog;

  setUpAll(() async {
    TestWidgetsFlutterBinding.ensureInitialized();
    catalog = ProcessSchemaCatalog();
    await catalog.load();
    // The loader swallows a missing or corrupt asset and leaves everything
    // empty, so without this guard every expectation below would pass vacuously.
    expect(catalog.isLoaded, isTrue,
        reason: 'assets/slicer/*.json did not load — the rest is vacuous');
  });

  /// The schema file read straight off disk, to compare against what the loader
  /// kept. Bypasses rootBundle on purpose: the question here is what was
  /// *dropped* during parsing.
  Map<String, dynamic> rawSchema() =>
      jsonDecode(File('assets/slicer/process-schema.json').readAsStringSync())
          as Map<String, dynamic>;

  group('loading', () {
    test('all three files parse into the catalog', () {
      expect(catalog.schema.length, greaterThan(300));
      expect(catalog.tree, hasLength(greaterThanOrEqualTo(6)));
      expect(catalog.toggles.rules.length, greaterThan(100));
      expect(catalog.toggles.locals.length, greaterThan(50));
    });

    test('concurrent loads share one attempt', () async {
      final fresh = ProcessSchemaCatalog();
      await Future.wait([fresh.load(), fresh.load(), fresh.load()]);
      expect(fresh.schema.length, catalog.schema.length);
    });

    test('a known option keeps every field the generator emitted', () {
      // accel_to_decel_factor is the compact case: a bounded percent with a
      // unit, so it exercises min/max/sidetext/default in one row.
      final option = catalog.schema['accel_to_decel_factor']!;
      expect(option.key, 'accel_to_decel_factor');
      expect(option.type, OptionType.coPercent);
      expect(option.mode, OptionMode.advanced);
      expect(option.label, 'accel_to_decel');
      expect(option.tooltip, isNotNull);
      expect(option.sidetext, '%');
      expect(option.min, 1);
      expect(option.max, 100);
      expect(option.defaultValue, 50);
    });

    test('an enum option carries index-aligned values and labels', () {
      final enums = catalog.schema.values
          .where((o) => o.type == OptionType.coEnum)
          .toList();
      expect(enums, isNotEmpty);
      for (final option in enums) {
        expect(option.enumValues, isNotEmpty,
            reason: '${option.key} is coEnum with no values to pick from');
        expect(option.enumLabels, hasLength(option.enumValues!.length),
            reason: '${option.key} labels do not line up with its values');
      }
    });
  });

  group('degrading rather than throwing', () {
    /// The real files, so a "corrupt one file" case is otherwise realistic.
    String onDisk(String name) =>
        File('assets/slicer/$name').readAsStringSync();

    Future<ProcessSchemaCatalog> loadWith(AssetReader reader) async {
      final catalog = ProcessSchemaCatalog(readAsset: reader);
      await catalog.load();
      return catalog;
    }

    test('an unreadable asset leaves an empty catalog, not an exception',
        () async {
      final loaded =
          await loadWith((key) => Future.error(Exception('no such asset')));
      expect(loaded.isLoaded, isFalse);
      expect(loaded.schema, isEmpty);
      expect(loaded.tree, isEmpty);
      expect(loaded.toggles.rules, isEmpty);
    });

    test('an asset that is not JSON leaves an empty catalog', () async {
      final loaded = await loadWith((key) async => 'not json at all');
      expect(loaded.isLoaded, isFalse);
    });

    test('valid JSON of the wrong shape leaves an empty catalog', () async {
      // The schema as a list and the tree as an object: both casts in the
      // decoder fail, which is the shape a mis-copied re-vendor would produce.
      final loaded = await loadWith((key) async => '[]');
      expect(loaded.isLoaded, isFalse);
    });

    test('a broken rule file still opens the screen, with nothing disabled',
        () async {
      // The documented fail-open decision, pinned: `isLoaded` deliberately
      // ignores the toggles. Renamed keys in a re-vendor parse to no rules,
      // which disables nothing — the same answer the evaluator gives for a
      // condition it cannot decide, and no reason to withhold 348 options.
      final loaded = await loadWith((key) async => switch (key) {
            'assets/slicer/process-toggle-rules.json' => '{"lokals": {}}',
            _ => onDisk(key.split('/').last),
          });
      expect(loaded.isLoaded, isTrue);
      expect(loaded.schema, isNotEmpty);
      expect(loaded.toggles.rules, isEmpty);
      expect(loaded.toggles.locals, isEmpty);
    });

    test('a failed attempt is not retried', () async {
      // A corrupt bundled asset does not become valid on the second tap, so the
      // load is latched either way. Without this, every open of the screen would
      // re-read and re-decode 156 KB to reach the same answer.
      var reads = 0;
      final catalog = ProcessSchemaCatalog(readAsset: (key) {
        reads++;
        return Future.error(Exception('boom'));
      });
      await catalog.load();
      await catalog.load();
      expect(reads, 3, reason: 'three assets, read once between them');
      expect(catalog.isLoaded, isFalse);
    });
  });

  group('schema and tree cover each other', () {
    test('every tree key exists in the schema', () {
      final missing = <String>[];
      for (final page in catalog.tree) {
        for (final group in page.groups) {
          for (final key in group.options) {
            if (!catalog.schema.containsKey(key)) missing.add(key);
          }
        }
      }
      expect(missing, isEmpty,
          reason: 'these would render as rows nothing can edit');
    });

    test('every schema key appears exactly once in the tree', () {
      final counts = <String, int>{};
      for (final page in catalog.tree) {
        for (final group in page.groups) {
          for (final key in group.options) {
            counts[key] = (counts[key] ?? 0) + 1;
          }
        }
      }
      final unreachable =
          catalog.schema.keys.where((k) => !counts.containsKey(k)).toList();
      final duplicated =
          counts.entries.where((e) => e.value > 1).map((e) => e.key).toList();

      expect(unreachable, isEmpty,
          reason: 'in the schema but on no page — no way to reach these');
      expect(duplicated, isEmpty,
          reason: 'on two pages — edits in one place would look lost in the other');
    });

    test('pages and groups are all named and non-empty', () {
      for (final page in catalog.tree) {
        expect(page.page, isNotEmpty);
        expect(page.groups, isNotEmpty, reason: '${page.page} has no groups');
        for (final group in page.groups) {
          expect(group.group, isNotEmpty, reason: 'unnamed group in ${page.page}');
          expect(group.options, isNotEmpty,
              reason: '${page.page}/${group.group} is empty');
        }
      }
    });
  });

  group('nothing is dropped on the way in', () {
    test('every option in the file has a type this app can render', () {
      final raw = rawSchema();
      final dropped =
          raw.keys.where((k) => !catalog.schema.containsKey(k)).toList();
      expect(dropped, isEmpty,
          reason: 'unknown OptionType — needs a control and a wire form in the '
              'codec before it can ship');
    });

    test('no option lands in a mode the app never shows', () {
      // `develop` is upstream's own dumping ground and is deliberately hidden,
      // but it is also what an *unrecognised* mode parses to — so a mode rename
      // upstream would quietly remove options. Anything here should be a real
      // `develop` entry in the file, nothing else.
      final raw = rawSchema();
      final hidden = catalog.schema.values
          .where((o) => o.mode == OptionMode.develop)
          .map((o) => o.key);
      for (final key in hidden) {
        expect((raw[key] as Map<String, dynamic>)['mode'], 'develop',
            reason: '$key is hidden because its mode was not recognised');
      }
    });

    test('bounds are numbers or the unresolved C++ expressions, nothing else', () {
      for (final option in catalog.schema.values) {
        for (final bound in [option.min, option.max]) {
          expect(bound, anyOf(isNull, isA<num>(), isA<String>()),
              reason: '${option.key} has a bound the codec cannot coerce');
        }
      }
    });

    test('every option has a default to fall back to', () {
      // The default is the last resort for what an untouched field shows, used
      // whenever the server cannot report the preset's own value.
      final missing = catalog.schema.values
          .where((o) => o.defaultValue == null)
          .map((o) => o.key)
          .toList();
      expect(missing, isEmpty);
    });
  });

  group('toggle rules', () {
    test('every rule names fields and a condition', () {
      for (final rule in catalog.toggles.rules) {
        expect(rule.fields, isNotEmpty);
        expect(rule.enableIf.trim(), isNotEmpty);
      }
    });

    test('rules only govern options the app knows about', () {
      final unknown = <String>{};
      for (final rule in catalog.toggles.rules) {
        for (final field in rule.fields) {
          if (!catalog.schema.containsKey(field)) unknown.add(field);
        }
      }
      // A rule for an option we do not render is harmless — but it means the
      // two files disagree, which is the signal that one of them is stale.
      expect(unknown, isEmpty,
          reason: 'toggle rules reference options the schema does not declare');
    });
  });

  group('OptionType', () {
    test('the vector types are exactly the per-extruder ones', () {
      final vectors =
          OptionType.values.where((t) => t.isVector).map((t) => t.name).toSet();
      expect(vectors, {'coBools', 'coFloats', 'coFloatsOrPercents'});
    });

    test('an unknown type is refused rather than guessed', () {
      expect(OptionType.tryParse('coPoint3'), isNull);
      expect(OptionType.tryParse(null), isNull);
      expect(OptionType.tryParse(7), isNull);
      expect(ProcessOption.tryFromJson('x', {'type': 'coPoint3'}), isNull);
    });
  });

  group('OptionMode', () {
    test('rank runs simple → develop', () {
      expect(OptionMode.simple.visibleAt(OptionMode.simple), isTrue);
      expect(OptionMode.advanced.visibleAt(OptionMode.simple), isFalse);
      expect(OptionMode.simple.visibleAt(OptionMode.expert), isTrue);
      expect(OptionMode.advanced.visibleAt(OptionMode.expert), isTrue);
      expect(OptionMode.expert.visibleAt(OptionMode.expert), isTrue);
    });

    test('develop is invisible at every tier the app offers', () {
      for (final selected in const [
        OptionMode.simple,
        OptionMode.advanced,
        OptionMode.expert,
      ]) {
        expect(OptionMode.develop.visibleAt(selected), isFalse);
      }
    });

    test('an unrecognised mode hides the option', () {
      expect(OptionMode.parse('wizard'), OptionMode.develop);
      expect(OptionMode.parse(null), OptionMode.develop);
    });
  });
}
